# -*- coding: utf-8 -*-
# Generated by Django 1.9.3 on 2016-03-19 04:45
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FacultyInCharge',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('designation', models.CharField(max_length=128)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='faculty_in_charge', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='FacultyVerification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('verification_key', models.UUIDField(default=uuid.uuid4)),
                ('verification_status', models.PositiveSmallIntegerField(choices=[(0, 'Pending'), (1, 'Verified'), (2, 'Rejected')], default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('citation', models.TextField(blank=True, null=True)),
                ('rejection_reason', models.TextField(blank=True, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('faculty_incharge', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='organizations', to='organization.FacultyInCharge')),
            ],
        ),
        migrations.CreateModel(
            name='OrganizationObject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Name of post', max_length=64)),
                ('object_type', models.PositiveSmallIntegerField(choices=[(0, 'Post'), (1, 'Award')], default=0)),
                ('max_recipients', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='posts_and_rewards', to='organization.Organization')),
            ],
            options={
                'verbose_name_plural': 'Posts and Awards',
                'verbose_name': 'Posts and Awards',
            },
        ),
        migrations.CreateModel(
            name='Recipient',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('requested_at', models.DateTimeField(auto_now_add=True)),
                ('organization_object', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recipients', to='organization.OrganizationObject')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='StudentLeader',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('designation', models.CharField(max_length=128)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_leader', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='StudentLeaderVerification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('verification_key', models.UUIDField(default=uuid.uuid4)),
                ('verification_status', models.PositiveSmallIntegerField(choices=[(0, 'Pending'), (1, 'Verified'), (2, 'Rejected')], default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('citation', models.TextField(blank=True, null=True)),
                ('rejection_reason', models.TextField(blank=True, null=True)),
                ('recipient', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='student_leader_verification', to='organization.Recipient')),
                ('verifier', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='verifications', to='organization.StudentLeader')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='organization',
            name='student_leader',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='organizations', to='organization.StudentLeader'),
        ),
        migrations.AddField(
            model_name='facultyverification',
            name='recipient',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='faculty_verification', to='organization.Recipient'),
        ),
        migrations.AddField(
            model_name='facultyverification',
            name='verifier',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='verifications', to='organization.FacultyInCharge'),
        ),
        migrations.AlterUniqueTogether(
            name='recipient',
            unique_together=set([('user', 'organization_object')]),
        ),
        migrations.AlterUniqueTogether(
            name='organizationobject',
            unique_together=set([('name', 'organization')]),
        ),
    ]
