# -*- coding: utf-8 -*-
# Generated by Django 1.9.3 on 2016-03-19 04:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='facultyverification',
            name='verification_key',
        ),
        migrations.RemoveField(
            model_name='studentleaderverification',
            name='verification_key',
        ),
        migrations.AddField(
            model_name='recipient',
            name='is_self_appraisal_public',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='recipient',
            name='self_appraisal',
            field=models.TextField(blank=True, null=True),
        ),
    ]
