# -*- coding: utf-8 -*-
# Generated by Django 1.9.3 on 2016-03-03 20:44
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FacultyVerification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('verification_key', models.UUIDField()),
                ('is_verified', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('verified_at', models.DateTimeField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='StudentLeaderVerification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('verification_key', models.UUIDField()),
                ('is_verified', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('verified_at', models.DateTimeField(null=True)),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='organizationobject',
            unique_together=set([('name', 'organization')]),
        ),
        migrations.RemoveField(
            model_name='recipient',
            name='is_verified_by_faculty',
        ),
        migrations.RemoveField(
            model_name='recipient',
            name='is_verified_by_student_leader',
        ),
        migrations.RemoveField(
            model_name='recipient',
            name='verified_by_faculty_at',
        ),
        migrations.RemoveField(
            model_name='recipient',
            name='verified_by_student_leader_at',
        ),
        migrations.AlterUniqueTogether(
            name='recipient',
            unique_together=set([('user', 'organization_object')]),
        ),
        migrations.AddField(
            model_name='studentleaderverification',
            name='recipient',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='student_leader_verification', to='organization.Recipient'),
        ),
        migrations.AddField(
            model_name='facultyverification',
            name='recipient',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='faculty_verification', to='organization.Recipient'),
        ),
    ]
