# -*- coding: utf-8 -*-
# Generated by Django 1.9.3 on 2016-03-03 21:29
from __future__ import unicode_literals

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0002_auto_20160304_0214'),
    ]

    operations = [
        migrations.AddField(
            model_name='organizationobject',
            name='max_recipients',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='facultyverification',
            name='verification_key',
            field=models.UUIDField(default=uuid.uuid4),
        ),
        migrations.AlterField(
            model_name='studentleaderverification',
            name='verification_key',
            field=models.UUIDField(default=uuid.uuid4),
        ),
    ]
