# -*- coding: utf-8 -*-
# Generated by Django 1.9.3 on 2016-03-20 09:17
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0002_auto_20160319_1024'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='recipient',
            options={'ordering': ['-requested_at']},
        ),
    ]
