# -*- coding: utf-8 -*-
# Generated by Django 1.9.3 on 2016-03-23 18:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0003_auto_20160320_1447'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organizationobject',
            name='max_recipients',
            field=models.PositiveIntegerField(default=100000),
        ),
    ]
