# -*- coding: utf-8 -*-
# Generated by Django 1.9.3 on 2016-03-04 07:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0004_auto_20160304_0528'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='organizationobject',
            name='is_post',
        ),
        migrations.AddField(
            model_name='organizationobject',
            name='object_type',
            field=models.PositiveSmallIntegerField(choices=[(0, 'Post'), (1, 'Award')], default=0),
        ),
        migrations.AlterField(
            model_name='facultyverification',
            name='verified_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='studentleaderverification',
            name='verified_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
