# -*- coding: utf-8 -*-
# Generated by Django 1.9.3 on 2016-03-04 14:43
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0006_auto_20160304_1234'),
    ]

    operations = [
        migrations.CreateModel(
            name='FacultyInCharge',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ldap_username', models.CharField(max_length=64)),
                ('designation', models.CharField(max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name='StudentLeader',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ldap_username', models.CharField(max_length=64)),
                ('designation', models.CharField(max_length=128)),
            ],
        ),
        migrations.RemoveField(
            model_name='organization',
            name='faculty_in_charge_username',
        ),
        migrations.RemoveField(
            model_name='organization',
            name='student_leader_username',
        ),
        migrations.AddField(
            model_name='facultyverification',
            name='rejection_reason',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='studentleaderverification',
            name='rejection_reason',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='facultyverification',
            name='verified_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='verifications', to='organization.FacultyInCharge'),
        ),
        migrations.AddField(
            model_name='studentleaderverification',
            name='verified_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='verifications', to='organization.StudentLeader'),
        ),
        migrations.AddField(
            model_name='organization',
            name='faculty_incharge',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='organizations', to='organization.FacultyInCharge'),
        ),
        migrations.AddField(
            model_name='organization',
            name='student_leader',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='organizations', to='organization.StudentLeader'),
        ),
    ]
