# -*- coding: utf-8 -*-
# Generated by Django 1.9.3 on 2016-03-04 14:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0007_auto_20160304_2013'),
    ]

    operations = [
        migrations.AddField(
            model_name='facultyincharge',
            name='name',
            field=models.CharField(max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='studentleader',
            name='name',
            field=models.CharField(max_length=128, null=True),
        ),
    ]
