# -*- coding: utf-8 -*-
# Generated by Django 1.9.3 on 2016-03-04 15:26
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0008_auto_20160304_2021'),
    ]

    operations = [
        migrations.RenameField(
            model_name='facultyverification',
            old_name='verified_by',
            new_name='verifier',
        ),
        migrations.RenameField(
            model_name='studentleaderverification',
            old_name='verified_by',
            new_name='verifier',
        ),
    ]
